steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/laurelin-backend:latest', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/laurelin-backend:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'laurelin-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/laurelin-backend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'FLASK_ENV=production,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GREENLIST_ENABLED=false'
      - '--set-secrets'
      - 'GOOGLE_CLIENT_ID=google-client-id:latest,SECRET_KEY=google-client-secret:latest'

images:
  - 'gcr.io/$PROJECT_ID/laurelin-backend:latest'
